name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2

      - name: Instalacja Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Instalacja potrzbenych rzeczy
        run: npm install

      - name: Uruchamianie testow
        run: npm test

      - name: Uruchamianie aplikacji
        run: npm start
