name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Instalacja Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalacja zależności
        run: npm install

      - name: Uruchamianie testów
        run: npm test

      - name: Uruchamianie aplikacji
        run: npm start
